name: Bug report
description: File a bug report
title: "[BUG]: <title> "
labels: ["BUG"]

body:
    - type: markdown
      attributes:
          value: "Thanks for taking the time to fill out this bug report!
          Please search ["Issues"](https://github.com/angsd/angsd/issues) to see if an issue already exists for the bug you encountered."
    - type: textarea
      id: what-happened
      attributes:
          label: What happened?
          description: What happened and what did you expect to happen?
          placeholder: Tell us what you see!
      validations:
          required: true
    - type: input
      id: version
      attributes:
          label: Version
          description: "Please specify your ANGSD and HTSlib version, i.e. `angsd 2>&1|head -1`"
          placeholder: "Version: "
      validations:
          required: true
    - type: textarea
      id: commands
      attributes:
          label: Relevant commands
          description: Please copy and paste any relevant commands you used. This will be automatically formatted into code, so no need for backticks. This will help us replicate the 
          render: bash
    - type: textarea
      id: logs
      attributes:
          label: Relevant log output
          description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
          render: bash
    - type: textarea
      id: reprex
      attributes:
          label: Minimal reproducible example
          description: "A [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) contains all components needed to reproduce the issue
          1) A small dataset, this can be a subset of the data you used
          2) Commands to reproduce the issue with given dataset"
